### ISSUE TITLE
No GUI interface, so in which file do I add the YAML?

### ISSUE THREAD

**Issue by cralwalker** [AlexxIT/SSHCommand#10]
RPi 4, Home Assistant 2022.11.2, Supervisor 2022.10.2, Operating System 9.3, Frontend 20221108.0 - latest

I am not seeing a GUI when I click on the integration to create a new ssh command.
In which file do I drop the YAML? 

I would like to create a button to execute the command?

**Comment by AlexxIT** [comment]
configuration.yaml
You can read more in Hass docs.

**Comment by cralwalker** [comment]
Works like a charm, thank you.
