### ISSUE TITLE
ssh_command.exec_command not available.

### ISSUE THREAD

**Issue by tung256** [AlexxIT/SSHCommand#12]
i installed and see the addon here \\192.168.1.229\config\custom_components\ssh_command
rebooted many times. 
still cant see the new service in Dev tab  http://192.168.1.229:8123/developer-tools/service
im on version Home Assistant 2022.9.0 .  Supervisor 2022.10.2 .

**Comment by AlexxIT** [comment]
Have you done configuration step?

**Comment by tung256** [comment]
you are right, i forgot that step was necessary.  thanks again for the amazing work with this add-on!
