### ISSUE TITLE
Store output in sensor

### ISSUE THREAD

**Issue by alanmilinovic** [AlexxIT/SSHCommand#13]
Is it possible to save command output (stdout) in sensor?

**Comment by alanmilinovic** [comment]
I checked the code and I can see that you are storing output into log as info and returning true at the end of the function. It would be very useful to return it back as a value that can be later on used.

**Comment by AlexxIT** [comment]
Check this https://github.com/AlexxIT/PythonScriptsPro
I have no plans to extend the functionality of this component. But you can solve the problem with my other component
