### ISSUE TITLE
225 char limit

### ISSUE THREAD

**Issue by alanmilinovic** [AlexxIT/SSHCommand#14]
I am getting "Invalid state encountered for entity ID: sensor.xxx. State max length is 255 characters."

Any idea how to solve it?

**Comment by AlexxIT** [comment]
This integration does not provide sensors

**Comment by alanmilinovic** [comment]
Sorry, I think I made issue in wrong repo. I am also using your PythonScriptsPro.

**Comment by AlexxIT** [comment]
In PythonScriptsPro you set the name manually with the `name` yaml parameter.

**Comment by alanmilinovic** [comment]
> In PythonScriptsPro you set the name manually with the `name` yaml parameter.

Hm, this is what I an doing now in python script.
`self.state = f"\n{ resp.decode() }"`

So I m using ssh command with python script pro.

Maybe I can set self.attributes instead? Not sure what is the syntax.

**Comment by AlexxIT** [comment]
Oh. It is about value of sensor. I thought is is about name of the sensor. You can do something like this:

```
self.state = f"\n{ resp.decode()[:250] }"
```

Also you may try to set:

```
self._attr_extra_state_attributes = { "response": resp.decode() }
```

**Comment by alanmilinovic** [comment]
Wow, that worked. Many thanks!
