### ISSUE TITLE
Feature request: Be able to use !secret

### ISSUE THREAD

**Issue by marceloaf** [AlexxIT/SSHCommand#16]
Hi! Hope this finds you well!

Wondering if you could implement the usage of !secret for user and password.

Best regards!
Marcelo

**Comment by AlexxIT** [comment]
I think it's already supported

**Comment by marceloaf** [comment]
> I think it's already supported

I tried it before posting this request. It is not supported yet. When you include the exclamation mark on the yaml, either for an automation or script it complains. If you enclose it in ' the service returns the error 'authentication failed'

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SSHCommand/releases/tag/v1.1.0
