### ISSUE TITLE
Support no password/user

### ISSUE THREAD

**Issue by vegedb** [AlexxIT/SSHCommand#17]
1. I have already setup SSH keys.
2. Using docker exec -it, I am able to ssh **without requiring password**. using this command 
`ssh pi@192.168.1.200' -i /config/.ssh/id_rsa`

Hope there's an option to just call service to run commands without any passwords

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SSHCommand/releases/tag/v1.1.0
