### ISSUE TITLE
Execute multiple commands in continuity

### ISSUE THREAD

**Issue by KirkKirk** [AlexxIT/SSHCommand#21]
Hi,

Is it possible to execute multiple commands in continuity?
After accessing the Cisco router, I want to enter "enable" mode and execute a command.
this is what should look like:

Line 1: username
Line 2: password
Line 3: en
Line 4: password
Line 5: reload 

As per current abilities, I can reach Line 3 but no further. 

Thanks,
Kirk

**Comment by AlexxIT** [comment]
Try this https://github.com/AlexxIT/PythonScriptsPro
