### ISSUE TITLE
Unable to run docker compose commands

### ISSUE THREAD

**Issue by robertwittmann** [AlexxIT/SSHCommand#24]
I'm able to connect to the host machine through ssh, and other commands work (tried creating and deleting folders, cause I'm not sure how to check any potential output like 'ls'), but when trying to run docker compose commands - like starting/stopping other services, nothing happens. 
Probably my understanding of the docker structure and commands that's faulty, but hope I can still find answers here.

**Comment by AlexxIT** [comment]
Maybe your user not allowed to do this.

There is another component that can return result
https://github.com/AlexxIT/PythonScriptsPro
