### ISSUE TITLE
Can you include the option for a response file?

### ISSUE THREAD

**Issue by Smarthome-Creator** [AlexxIT/SSHCommand#25]
I did some testing and found that your integration allows you to run SSH commands that take longer than 60 seconds and would otherwise be "killed" by HA.
That's very cool. Could you add the option to get the "stdout", "stderr" and "exitcode" back?
Then you could have the log sent to you in case of problems.

**Comment by AlexxIT** [comment]
I don't want add this to this integration so it can be used in very old hass versions.
But you can use this integration and get what you want
https://github.com/AlexxIT/PythonScriptsPro

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SSHCommand/releases/tag/v1.2.0

I've added support for the answer for the newer versions while keeping support for the older HA versions
