### ISSUE TITLE
 private_key' is an invalid option for 'ssh_command

### ISSUE THREAD

**Issue by AJolly** [AlexxIT/SSHCommand#31]
Can't store the private_key in configuration.yaml.

Invalid config for 'ssh_command' at configuration.yaml, line 641: 'private_key' is an invalid option for 'ssh_command', check: ssh_command->private_key

**Comment by AlexxIT** [comment]
The error is correct. There should be no such key inside `ssh_command`.

**Comment by AJolly** [comment]
Then how do we set a default option for the SSH key, like we can set a default for the password?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SSHCommand/releases/tag/v1.2.0
