### ISSUE TITLE
Добавить возможность выполнять команды по telnet

### ISSUE THREAD

**Issue by AlexQuaken** [AlexxIT/SSHCommand#6]
Будет также очень полезно, например, для плановой перезагрузки gateway3.
Со временем они имеют свойство отваливаться...

**Comment by AlexxIT** [comment]
Gateway3 можно перезагружать удалённо
https://github.com/AlexxIT/XiaomiGateway3#advanced-commands

**Comment by AlexQuaken** [comment]
> Gateway3 можно перезагружать удалённо
> https://github.com/AlexxIT/XiaomiGateway3#advanced-commands

Спасибо, освежил доку в памяти, однако все-таки существуют железки в которых есть только telnet, возможно добавить еще один протокол в интеграцию ?
