### ISSUE TITLE
Uknown error on call service

### ISSUE THREAD

**Issue by sunhort** [AlexxIT/SSHCommand#8]
Не удалось вызвать службу ssh_command.exec_command. Unknown error
Strange because I did run docker exec -it homeassistant bash and added ssh keys to docker hass image by typing "yes" on first connect, and ssh works fine from inside the docker hass. For some reason plugin gives an error.

**Comment by AlexxIT** [comment]
Have you setup the integration?

**Comment by sunhort** [comment]
Yes, it's added to integrations and scripts are set with GUI, my bad was missing string "service: ssh_command.exec_command" reason it would not appear while switching to yaml mode, but I could see it from the example. Thanks again for this great addon!
