### ISSUE TITLE
Иногда вызывает рестарт HA

### ISSUE THREAD

**Issue by AlexQuaken** [AlexxIT/SSHCommand#9]
Иногда вызывает рестарт HA, какой-то системы не обнаружил. В логах HA  ничего по этому поводу нет.

  - platform: wake_on_lan
    name: Mi TV 4S
    mac: 'EC:FA:5C:FD:FE:АB'
    host: 192.168.0.49
    turn_off:
      - service: ssh_command.exec_command
        data:
          host: 192.168.0.6
          port: 22
          user: !secret nuc_username
          pass: !secret nuc_password
          command: 'adb connect 192.168.0.49:5555 && adb shell input keyevent 26 && adb disconnect'

**Comment by dmunsh** [comment]
У меня не иногда, а при каждом вызове службы
  - service: ssh_command.exec_command
    data:
      host: 192.168.1.2
      port: 22
      user: ****
      pass: ****
      command: poweroff

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
